format = """
[](#6272A4)\
$directory\
[](fg:#6272A4 bg:#FF79C6)\
$git_branch\
$git_status\
[](fg:#FF79C6 bg:#8BE9FD)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#8BE9FD bg:#FFB86C)\
$direnv\
[](fg:#FFB86C bg:#50FA7B)\
$cmd_duration\
[](fg:#50FA7B)\
\n$character
"""

# Enable/disable the blank line at the start of the prompt
add_newline = false

# Set timeout for commands
command_timeout = 1000

[character]
format = "$symbol"
success_symbol = "[  󱞪 ❯❯❯](bold green)  "
error_symbol = "[  󱞪 ❯❯❯](bold red)  "

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#44475A"
style_root = "bg:#44475A"
format = '[ ]($style)'

[directory]
style = "bg:#6272A4 fg:#F8F8F2"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "…/"
read_only = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = " "
".config" = "  "
"config" = "  "
"Config" = "  "
"Books" = " 󱉟 "
"Data" = "  "
"Desktop" = "  "
"Documents" = " 󰈙 "
"Finances" = "  "
"Downloads" = "  "
"Games" = "  "
"Git" = " 󰊢"
"PrismLauncher" = " 󰍳 "
"Steam" = "  "
"ISOs" = " 󰗮 "
"Music" = "  "
"Spotify" = "  "
"Pictures" = "  "
"Personal" = "  "
"System" = "  "
"Videos" = "  "
"dropbox" = "  "
"google-drive" = "  "
"onedrive" = "  "
"Attachments" = " 󰁦 "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[direnv]
symbol = "  "
style = "bg:#FFB86C fg:#282A36"
format = "[ $symbol$loaded/$allowed ]($style)"
disabled = false

[c]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 0
style = "bg:#50FA7B fg:#282A36"
format = '[ 󱎫 $duration ]($style)'
show_notifications = true
min_time_to_notify = 5_000

[docker_context]
symbol = " "
style = "bg:#FFB86C fg:#282A36"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FF79C6 fg:#282A36"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FF79C6 fg:#282A36"
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8BE9FD fg:#282A36"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%X" # Hour:Minute Format
style = "bg:#FFB86C"
format = '[[  $time ](bg:#FFB86C)]($style)'
