# Use the color palette
palette = "dracula"

format = """
[](comment)\
$directory\
[](fg:comment bg:pink)\
$git_branch\
$git_status\
[](fg:pink bg:cyan)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:cyan bg:orange)\
$direnv\
[](fg:orange bg:green)\
$cmd_duration\
[](fg:green)\
\n$character
"""

# Enable/disable the blank line at the start of the prompt
add_newline = false

# Set timeout for commands
command_timeout = 1000

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[character]
format = "$symbol"
success_symbol = "[  󱞪 ❯❯❯](bold green)  "
error_symbol = "[  󱞪 ❯❯❯](bold red)  "

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:current_line"
style_root = "bg:current_line"
format = '[ ]($style)'

[directory]
style = "bg:comment fg:foreground"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "…/"
read_only = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = " "
".config" = "  "
"config" = "  "
"Config" = "  "
"Books" = " 󱉟 "
"Data" = "  "
"Desktop" = "  "
"Documents" = " 󰈙 "
"Finances" = "  "
"Downloads" = "  "
"Games" = "  "
"Git" = " 󰊢"
"PrismLauncher" = " 󰍳 "
"Steam" = "  "
"ISOs" = " 󰗮 "
"Music" = "  "
"Spotify" = "  "
"Pictures" = "  "
"Personal" = "  "
"System" = "  "
"Videos" = "  "
"dropbox" = "  "
"google-drive" = "  "
"onedrive" = "  "
"Attachments" = " 󰁦 "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[direnv]
symbol = "  "
style = "bg:orange fg:background"
format = "[ $symbol$loaded/$allowed ]($style)"
disabled = false

[c]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 0
style = "bg:green fg:background"
format = '[ 󱎫 $duration ]($style)'
show_notifications = true
min_time_to_notify = 5_000

[docker_context]
symbol = " "
style = "bg:orange fg:background"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:pink fg:background"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:pink fg:background"
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:cyan fg:background"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%X" # Hour:Minute Format
style = "bg:orange"
format = '[[  $time ](bg:orange)]($style)'
