#!/usr/bin/env bash
# Check if screen is not currently locked
if ! pgrep -x "i3lock" > /dev/null
then
    # Restart session
    $HOME/.scripts/session.sh --restart &
fi

# Disable & Re-Enable Compositor
$HOME/.scripts/picom.sh --on &

# NVIDIA Force Composition Pipeline
/usr/bin/nvidia-force-comp-pipeline &

# Restore wallpaper
/usr/bin/nitrogen --restore &

# Update lock screen wallpaper
/usr/bin/betterlockscreen -u \
    $HOME/Data/NextCloud/Wallpapers/Desktop/Solar_System.png &
