configs:
  # MANDATORY: name of the snapper config
  - name: root
    # MANDATORY: borg repo target, e. g. backupuser@backuphost:reponame
    repo: /run/media/sravan/5TB_HDD/Backups/oryp7-gentoo/root
    # if this is set to true, borg does not neccessarily fail when a backup fails
    fault_tolerant_mode: true
    # snapborg fails when the most recent snapshot transferred successfully is
    # older than the time period given here. Set to '0d' to disable this behaviour
    last_backup_max_age: 0d
    # archive creation/storage options
    storage:
      # use either none or repokey encryption, defaults to none
      encryption: none
      # MANDATORY when using repokey: literal key passphrase or path to file
      # containing the key passphrase. Ignored when using none encryption
      encryption_passphrase: ~
      # compression configuration, see borg manual
      compression: auto,zstd,4
    retention:
      keep_last: 15
      keep_hourly: 0
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 1
      keep_yearly: 1
    # exclude patterns (see borg help patterns)
    exclude_patterns: []
