# ~/.config/starship.toml

# Don't print a new line at the start of the prompt
add_newline = false

format = "[◆](bold green) $all"

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[character]
format = "$symbol"
success_symbol = "[❯](bold purple)[❯](bold cyan)[❯](bold green) "
error_symbol = "[❯❯❯](bold red) "

[cmd_duration]
min_time = 10_000

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
read_only = ""

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[line_break]
disabled = false

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
